image: 
  name: bonanzhu/aiida_core_base:0.12.2-dev
  

before_script:
    - apt-get update
    # Disable interactive configuration of tzdata
    #- DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql-all 
    #- apt-get install -y mlocate && updatedb
    - export HOME=/home/aiida
    - export PATH=$HOME/.local/bin:$PATH
    - pip install --upgrade --user pip
    - pip install --user -e .
    - reentry scan -r aiida

pytest_tests:
  variables:
    DB_HOST: "postgres"
  services:
    - postgres:9.5
  script:
    - pip install --user pytest
    - su -c '/home/aiida/.local/bin/pytest aiida_castep/tests' aiida

db_tests:
  variables:
    DB_HOST: "postgres"
  services:
    - postgres:9.5
  script:
    - TEST_AIIDA_BACKEND="django" bash .ci-data/setup_profiles.sh
    - verdi -p test_django devel tests db.castep
    - TEST_AIIDA_BACKEND="sqlalchemy" bash .ci-data/setup_profiles.sh
    - verdi -p test_sqlalchemy devel tests db.castep
