image: 
  name: aiidateam/aiida_core_base:latest-1.0
  
before_script:
  - apt-get update
  - apt-get install make
  # Disable interactive configuration of tzdata
  #- DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql-all 
  #- apt-get install -y mlocate && updatedb
  - export HOME=/home/aiida
  - export PATH=$HOME/.local/bin:$PATH
  - pip install sphinx sphinx_rtd_theme
  - $HOME/.venv-py2/bin/pip install --no-cache-dir --no-build-isolation --editable .
  - $HOME/.venv-py3/bin/pip install --no-cache-dir --no-build-isolation --editable .
  - $HOME/.venv-py3/bin/reentry scan -r aiida
  - $HOME/.venv-py2/bin/reentry scan -r aiida

pytest_tests3:
  variables:
    DB_HOST: "postgres"
  script:
    - $HOME/.venv-py3/bin/pip install pytest
    - su -c '/home/aiida/.local/bin/pytest aiida_castep/tests' aiida
  services:
    - postgres:10


pytest_tests2:
  variables:
    DB_HOST: "postgres"
  script:
    - $HOME/.venv-py2/bin/pip install pytest
    - su -c '/home/aiida/.local/bin/pytest aiida_castep/tests' aiida


doc_build2:
  variables:
    DB_HOST: "postgres"
  script:
    # The profile needs to be there for the building of docs
    - TEST_AIIDA_BACKEND="django" bash .ci-data/setup_profiles.sh
    - cd docs
    - source $HOME/.venv-py2/bin/activate
    - make

doc_build3:
  variables:
    DB_HOST: "postgres"
  script:
    # The profile needs to be there for the building of docs
    - TEST_AIIDA_BACKEND="django" bash .ci-data/setup_profiles.sh
    - cd docs
    - source $HOME/.venv-py3/bin/activate
    - make

db_tests2:
  variables:
    DB_HOST: "postgres"
  script:
    - source $HOME/.venv-py2/bin/activate
    - TEST_AIIDA_BACKEND="django" bash .ci-data/setup_profiles.sh
    - verdi -p test_django devel tests db.castep
    - TEST_AIIDA_BACKEND="sqlalchemy" bash .ci-data/setup_profiles.sh
    - verdi -p test_sqlalchemy devel tests db.castep

db_tests3:
  variables:
    DB_HOST: "postgres"
  script:
    - source $HOME/.venv-py3/bin/activate
    - TEST_AIIDA_BACKEND="django" bash .ci-data/setup_profiles.sh
    - verdi -p test_django devel tests db.castep
    - TEST_AIIDA_BACKEND="sqlalchemy" bash .ci-data/setup_profiles.sh
    - verdi -p test_sqlalchemy devel tests db.castep

    
